### PR TITLE
Update README.MD for General Squad Framework with Examples

### PR DESCRIPTION
**Pull request by tenfinney**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
I have lots of thoughts on this:
- Let's keep this simple! Currently it's a very long digest with lots of non-essential information. Let's try to keep this 3 paragraphs or less (guesstimation), and not create needless friction and beurocracy at the document level. Pragmatic documentation > verbose and overly explicit.
- For the example, we can create a __TEMPLATE__.md file like we did in the spending-proposals directory. No need to have the sample embedded in the README (taking up yet more room).
- The main goal of this README should just be to orient people ("Here are our squads. This is what they are fore. Here's how squads affect you, and how you can get in contact.")

**Comment by dOrgJelli** [comment]
The goal is to allow contributors to get acquainted with the team members leading various parts of the project, so they can get involved themselves. It should be up to the individual on how they choose to do this, no need for sign-up forms + explicit steps. Just point them to the squads, and tell them to feel free to DM any of the points of contact to get involved in a squad.

**Comment by tenfinney** [comment]
I will cut from the bottom up leaving some basic information as you suggested.

**Comment by tenfinney** [comment]
I will cut from the bottom up leaving some basic information as you suggested.

**Pull request merged**
